#!/bin/bash
cd `dirname $0`
FILE=SUMMARY.md.bak
if [ -f $FILE ]; then
    rm -rf SUMMARY.md
    mv SUMMARY.md.bak SUMMARY.md
git pull
mv SUMMARY.md SUMMARY.md.bak
cp SUMMARY-tsa.md SUMMARY.md
gitbook build
